### PR TITLE
Added ECAI

### PR DESCRIPTION
**Pull request by tranhungnghiep**
Top 3 conferences in general AI together with AAAI and IJCAI. On the rise in recent years with joint IJCAI-ECAI'18 and a record number of submissions to ECAI'20.

### CODE REVIEW

**Comment by lixin4ever** [comment]
Thanks for your contribution. I think AAAI and IJCAI are representative enough for general AI conferences.

**Comment by tranhungnghiep** [comment]
Thanks, but in my humble opinion, perhaps the list should extensively include AI conferences. ECAI in AI is to some extents similarly to EACL/NAACL in NLP or ECCV/ICCV in CV, which are included.

However, if you do not want to merge, I totally understand and respect your opinion. In that case, I will maintain a separate fork for better coverage.

**Comment by tranhungnghiep** [comment]
P.S. [The extended fork is here](https://github.com/tranhungnghiep/Conference-Acceptance-Rate-Extended/) and will add some main conferences. You are free to pull/merge anytime. Hope that we can both help contributing useful information for everyone.

**Comment by lixin4ever** [comment]
Your suggestions are reasonable and I have removed the EACL items from the table. As with adding new items, my idea is to keep the table as simple as possible and thus only listing the most representative (or the most well-known) conferences should be enough. Thanks again for your contribution.

**Comment by tranhungnghiep** [comment]
I understand your opinion about a simple representative list and I value our diverse views. My list still contains EACL, with added CoNLL in nlp, ISWC and ESWC in semantics web, among others. I prefer utility, and have read many good and important papers in these venues, thus their presences are guaranteed in my list. Thank you for your original contribution. Let's keep up our good work.

**Pull request closed without merging**
